(define (domain gripper-strips)
 (:requirements :strips :typing)
 (:predicates (room ?r)
 (ball ?b)
 (gripper ?g)
 (at-robby ?r)
 (at ?b ?r)
 (free ?g)
 (carry ?o ?g))
 (:action move
  :parameters ( ?from ?to)
  :precondition (and (room ?from) (room ?to) (at-robby ?from))
  :effect (and (at-robby ?to) (not (at-robby ?from))))
 (:action dynamicmacro_eff_3
  :parameters ( ?obj ?room ?tox3)
  :precondition (and (ball ?obj) (room ?room) (at ?obj ?room) (at-robby ?room) (room ?tox3))
  :effect (and (at-robby ?tox3) (at ?obj ?tox3) (not (at ?obj ?room)) (not (at-robby ?room))))
)
